### ISSUE TITLE
All acronyms should be same cased

### ISSUE THREAD

**Issue by haron68** [Solomon04/go-docker#1]
- ~`Uuid`~ ❌
- ~`uuid`~ ❌
- `UUID` ✅
- `uuid` ✅
- `userUUID` not ~`userUuid`~ 
- `userID` not ~`userId`~

Acronym variables always have the acronym come at the end of the variable phrase
- `userUUID` not `UUIDuser`

https://github.com/Solomon04/go-docker/blob/86af444ea9ac16b99c5bcd89f0ef736498723ff1/src/db/models.go#L12

**Comment by haron68** [comment]
Always use `PascalCase` for mysql.

**Comment by Solomon04** [comment]
This is from the sql compiler

**Comment by haron68** [comment]
I suppose let's choose a precedent to follow and stick with it. So long as the practice is consistent I don't care.

**Comment by haron68** [comment]
We will use same case for all code that's not generated to stay consistent with our own practices
