### ISSUE TITLE
Remove 'me' query

### ISSUE THREAD

**Issue by haron68** [Solomon04/go-docker#5]
https://github.com/Solomon04/go-docker/blob/86af444ea9ac16b99c5bcd89f0ef736498723ff1/graph/schema.graphql#L183

- This is an opinionated issue but I think we should keep a third-person paradigm when we work with our users because the functionality of getting the "me" user is done by the `user` query as demonstrated in our initial meeting. This reduces redudancy

**Comment by Solomon04** [comment]
In your demo didn't you require that the user pass in their uuid  like so `user(uuid: ID): User` 

I drew inspiration to use a me query because my job had done the same thing with their [user service](http://services-dev.petfinder.com/)

**Comment by haron68** [comment]
My implementation did not require a uuid be passed. Not passing a uuid implies you’re trying to query the signed in user’s information. Passing a uuid would get any user’s info who exists.

**Comment by Solomon04** [comment]
Right, but don't you think it's better to be explicit about it? With the current setup we have to imply that we don't have to pass the param in

**Comment by haron68** [comment]
It is bad to be explicit about it because it is inconsistent and introduces unnecessary redundancy. It is simpler to imply it and it intuitively flows from a 3rd person point of view with respect to the user. Consider the sentence "get this user" vs "get this me". It would be simpler to serve users from a 3rd person POV because it reduces the chance of redundant code being written.
